### ISSUE TITLE
Github Profile links on Alumni Page not added

### ISSUE THREAD

**Issue by dhairyashah1** [SRA-VJTI/sra-vjti.github.io#10]
The respective GitHub profile URLs on this page [https://sravjti.in/teams/alumni](https://sravjti.in/teams/alumni) are not added. They redirect to the same page.

**Comment by kkothari2001** [comment]
https://github.com/SRA-VJTI/sra-vjti.github.io/commit/021e62d5f7223ef8eae33913f137a8d6b93abac7
