### ISSUE TITLE
Remove the GitHub link from prof page, add the LinkedIn links

### ISSUE THREAD

**Issue by ombhilare999** [SRA-VJTI/sra-vjti.github.io#11]
![image](https://user-images.githubusercontent.com/40693854/122711317-98225b00-d27f-11eb-9c7a-a05b2c98efb5.png)

Remove the GitHub link from the prof page, add the LinkedIn links

[Dr. A. S. Rao](https://www.linkedin.com/in/dr-a-s-rao-a82aa620?originalSubdomain=in)
[Dr. V. B. Suryawanshi](https://www.linkedin.com/in/dr-vinod-suryawanshi-b02a8515/?originalSubdomain=in)
[Dr. S. A. Mastud](https://www.linkedin.com/in/sachin-mastud-670602206/?originalSubdomain=in)

**Comment by kkothari2001** [comment]
@ombhilare999 I have added conditional rendering of all the person classes so the links will appear only entered in the data. Will add LinkedIn links for profs in a separate commit.

**Comment by kkothari2001** [comment]
Solved

**Comment by kkothari2001** [comment]
Solved
