### ISSUE TITLE
Add Github and youtube links in Activities page

### ISSUE THREAD

**Issue by ombhilare999** [SRA-VJTI/sra-vjti.github.io#15]
[WallE github](https://github.com/SRA-VJTI/Wall-E_v2.2)
[WallE Youtube](https://www.youtube.com/watch?v=-AbwiFBjHl0&t=36s)

[Mario github](https://github.com/SRA-VJTI/ROS-Workshop-2.1)
[Mario Youtube](https://www.youtube.com/watch?v=qkdTsRB-te4)

**Comment by kkothari2001** [comment]
I have not defined a link section on the activities page. Will work on it separately.

**Comment by ombhilare999** [comment]
Solved here #33
