### ISSUE TITLE
Add startup section

### ISSUE THREAD

**Issue by VedantParanjape** [SRA-VJTI/sra-vjti.github.io#24]
This section should be similar to the internship experience section in terms of format. Cards which will have short details about the startup, and on pressing the card, it will redirect to the company website.

Feel free to make changes to enhance this.

**Comment by ombhilare999** [comment]
1. Aditya Sengupta: Instamojo (https://www.instamojo.com/)
2. Rohit Bhaskar: Creto (https://www.creto.club/)
