### ISSUE TITLE
Change ico from vercel to SRA logo

### ISSUE THREAD

**Issue by VedantParanjape** [SRA-VJTI/sra-vjti.github.io#4]
![Screenshot from 2021-06-12 22-52-25](https://user-images.githubusercontent.com/22630228/121784317-f3de4b80-cbd0-11eb-85cc-5fb0812e6ebe.png)

Replace the vercel icon with SRA Khopdi baba logo

**Comment by kkothari2001** [comment]
Working on it.

**Comment by kkothari2001** [comment]
![image](https://user-images.githubusercontent.com/53650538/121793733-d7b5cb00-cc1f-11eb-807d-1fcdce28413f.png)
Seems to work. Satisfactory?

**Comment by kkothari2001** [comment]
You may need to reset cokkies to see the new favicon

**Comment by VedantParanjape** [comment]
@kkothari2001 on Firefox its still the same

**Comment by kkothari2001** [comment]
Yes @VedantParanjape that caching of the favicon is a common thing in many browsers, maybe try removing the cache and retrying.
