### ISSUE TITLE
Add SRA talks section

### ISSUE THREAD

**Issue by gautam-dev-maker** [SRA-VJTI/sra-vjti.github.io#49]
We need a section for SRA talks inside Activities that contains the list of previous sessions. It should also include the tags to show the domain of the talk.

**Comment by Jamm02** [comment]
https://github.com/SRA-VJTI/sra-vjti.github.io/commit/ff90467aee2c0aaf85f1548643369ec515026e76

Merged.

**Comment by kkothari2001** [comment]
Thanks
