### ISSUE TITLE
Add a new `Seminars` section under Activities

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/sra-vjti.github.io#65]
Create a new section of `Seminars` under the `Activities` tab.
This section should include the descriptions of the following seminars:

- Inception/Basic of Coding
- PIXELS
- DIMENSION

**Comment by Dhruv454000** [comment]
> @Dhruv454000 is this issue taken?

No

**Comment by kkothari2001** [comment]
Simple task.
Allot to SY.

**Comment by kkothari2001** [comment]
@MOLOCH-dev @Jamm02 pls also review the content

**Comment by VedantParanjape** [comment]
Why not use PR posters in that static image instead of robo dance.

**Comment by labeeb-7z** [comment]
updated : 
![image](https://user-images.githubusercontent.com/94868003/203290406-e4a933ff-de74-4a6e-b1e0-5278e20c42fa.png)
