### ISSUE TITLE
Add Sponsor Us Section to the Website

### ISSUE THREAD

**Issue by toshan-luktuke** [SRA-VJTI/sra-vjti.github.io#80]
In the Sponsors page, we can add a Sponsor Us section below our sponsors.
Things to include:
1. Sponsorship Brochure
2. Contact Us
3. Deliverables we offer

If possible just include the brochure in a PR soon, the rest can be done as time allows

**Comment by kkothari2001** [comment]
We can use a modal popup to show all this info once te button is clicked

**Comment by SuperChamp234** [comment]
This task has been assigned to Zain, Labib and Sameer by Dhruv. We're working on it.

**Comment by sameergupta4873** [comment]
Would love to work on the issue

**Comment by aPR0T0** [comment]
Would like to work on this too

**Comment by Jash-Shah** [comment]
As part of this can also add an Alumni Reach section that showcases the institutions that SRA Alumni are a part of. This is separate from the `Alumni` section under the `Teams` tab. Helpful while seeking Sponsorship/Partnership.

- Can be divided into companies, universities, and research laboratories.
- Image tiles with links to the home page of the companies and the name of Alumni should suffice.

**Comment by kkothari2001** [comment]
@Jash-Shah we can do this once we get done with the drop-down buttons on the navbar, that'll free up space for more pages.
