### ISSUE TITLE
Change Espressif Logo in Sponsors Section

### ISSUE THREAD

**Issue by toshan-luktuke** [SRA-VJTI/sra-vjti.github.io#89]
Currently the Espressif logo only has the company logo.

It is suggested to change the logo to one that has both the name 'Espressif' as well as the logo

**Comment by SuperChamp234** [comment]
This task has been assigned to Zain, Labib and Sameer by Dhruv. We're working on it.

**Comment by kkothari2001** [comment]
One of the three, start working on this. I can't assign one task to three people na. Have the setup instructions been relayed?

**Comment by sameergupta4873** [comment]
I would like to work on this issue, is this logo is a good replacement ? [new logo](http://burakcaliskan.org/blog/depo/2017/05/esp.png)

**Comment by kkothari2001** [comment]
Create a PR, with screenshots. Try looking for a logo with transparent background if possible.

Would white be more preferable to you? @toshan-luktuke

**Comment by toshan-luktuke** [comment]
Better to use Espressif's official font in the logo. 
![image](https://user-images.githubusercontent.com/31101072/200188353-9b545981-b2c3-4bc8-bdec-06453ebff86e.png)
This can work imo

**Comment by toshan-luktuke** [comment]
You can use online tools to turn a white background into a transparent one, to be on the safe side with the website, try testing both how a transparent background and a white one look

**Comment by kkothari2001** [comment]
Aah perfect, crop it up into a tight square @sameergupta4873

**Comment by sameergupta4873** [comment]
ok i will use the Espressif's official font , here is the ss of transparent with black background old logo :- 
<img width="1440" alt="Screenshot 2022-11-06 at 11 58 10 PM" src="https://user-images.githubusercontent.com/95731926/200188562-f5107865-ccd6-4993-bdcf-8a6c90de3185.png">

**Comment by sameergupta4873** [comment]
also should i change the logo in the industrial reach section ?

**Comment by sameergupta4873** [comment]
White background SS :- 
<img width="1440" alt="Screenshot 2022-11-07 at 12 15 36 AM" src="https://user-images.githubusercontent.com/95731926/200189249-b369871a-517e-4173-bbe7-886ddd786eb1.png">

**Comment by sameergupta4873** [comment]
transparent background ss:- 
<img width="1440" alt="Screenshot 2022-11-07 at 12 38 43 AM" src="https://user-images.githubusercontent.com/95731926/200190165-63380fb0-8c02-4d41-a3d4-4d56abb417c0.png">

**Comment by sameergupta4873** [comment]
which seems fine @toshan-luktuke

**Comment by toshan-luktuke** [comment]
Transparent looks better imo :+1:

**Comment by sameergupta4873** [comment]
should I send a pr for that ?

**Comment by toshan-luktuke** [comment]
Yepp, go ahead

**Comment by kkothari2001** [comment]
Solved in #90
