### ISSUE TITLE
Change University Admits to University Reach

### ISSUE THREAD

**Issue by kkothari2001** [SRA-VJTI/sra-vjti.github.io#91]
...and thus add Universities in which we have interned too, like Edinburgh.

I think the assigned person can look at an old commit to see the list of universities we used to have (some of which were removed at the previous switch to "University Admits"

![image](https://user-images.githubusercontent.com/53650538/200252543-a2bb796f-307f-40e4-ad74-957593856d7f.png)

**Comment by kkothari2001** [comment]
And also add Apple to our industrial reach

**Comment by sameergupta4873** [comment]
Ok, Can i work on this issue

**Comment by kkothari2001** [comment]
Sure, just directly create a PR with screenshots over there
