### ISSUE TITLE
Add title to each page

### ISSUE THREAD

**Issue by labeeb-7z** [SRA-VJTI/sra-vjti.github.io#96]
Currently each page's title is its URL, add a title for every page

**Comment by labeeb-7z** [comment]
Is this fine?
![image](https://user-images.githubusercontent.com/94868003/203295264-4c27996e-8f58-4ea8-9146-fa827021b806.png)
should i remove | SRA VJTI from each page?

**Comment by kkothari2001** [comment]
This is fine.
